app/models/User.php
<?php

/**
 * This is the model class for table "tp.tp_user".
 *
 * The followings are the available columns in table 'tp.tp_user':
 * @property integer $id
 * @property integer $tm_id
 * @property string $nick
 * @property string $email
 * @property string $password
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property string $sex
 * @property integer $city
 * @property integer $country
 * @property string $city_other
 * @property string $date_create
 * @property string $my_updated
 * @property string $avatar_ext
 * @property string $birthday
 * @property string $icq
 * @property string $www
 * @property string $profession
 * @property string $phone
 * @property boolean $active
 * @property boolean $show_email
 * @property boolean $show_icq
 * @property string $description
 * @property string $interests
 * @property boolean $manager
 * @property string $company
 * @property integer $stage
 * @property integer $reg_proj
 * @property string $specs
 * @property integer $specialization_id
 * @property integer $password_strength
 * @property boolean $news_subscription_tophotels
 * @property boolean $news_subscription_turpoisk
 * @property boolean $news_subscription_rutraveler
 * @property boolean $news_subscription_travelview
 * @property boolean $news_subscription_traveltalk
 * @property boolean $news_subscription_travelpassport
 * @property boolean $confirmed
 * @property string $updated
 * @property boolean $trash
 * @property integer $hp_id
 * @property string $hp_updated
 * @property integer $agent_ti_id
 * @property boolean $news_subscription_hotelsbroker
 * @property boolean $not_show_age
 */
class User extends CActiveRecord {
    const AVATAR_SIZE_25 = 25,
        AVATAR_SIZE_50 = 50,
        AVATAR_SIZE_100 = 100,
        AVATAR_SIZE_290 = 290;

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'tp.tp_user';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('nick, email, password, city, country, date_create, my_updated, updated', 'required'),
            array('tm_id, city, country, stage, reg_proj, specialization_id, password_strength, hp_id, agent_ti_id', 'numerical', 'integerOnly' => true),
            array('nick, email, name, surname, patronymic, city_other, www, interests, company, specs', 'length', 'max' => 255),
            array('password', 'length', 'max' => 32),
            array('avatar_ext', 'length', 'max' => 5),
            array('icq, profession, phone', 'length', 'max' => 100),
            array('sex, birthday, active, show_email, show_icq, description, manager, news_subscription_tophotels, news_subscription_turpoisk, news_subscription_rutraveler, news_subscription_travelview, news_subscription_traveltalk, news_subscription_travelpassport, confirmed, trash, hp_updated, news_subscription_hotelsbroker, not_show_age', 'safe'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'co' => array(self::BELONGS_TO, 'DictCountry', 'country'),
            'ct' => array(self::BELONGS_TO, 'DictCity', 'city'),
            'dop' => array(self::HAS_ONE, 'UserDop', 'id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'tm_id' => 'Tm',
            'nick' => 'Nick',
            'email' => 'Email',
            'password' => 'Password',
            'name' => 'Name',
            'surname' => 'Surname',
            'patronymic' => 'Patronymic',
            'sex' => 'Sex',
            'city' => 'City',
            'country' => 'Country',
            'city_other' => 'City Other',
            'date_create' => 'Date Create',
            'my_updated' => 'My Updated',
            'avatar_ext' => 'Avatar Ext',
            'birthday' => 'Birthday',
            'icq' => 'Icq',
            'www' => 'Www',
            'profession' => 'Profession',
            'phone' => 'Phone',
            'active' => 'Active',
            'show_email' => 'Show Email',
            'show_icq' => 'Show Icq',
            'description' => 'Description',
            'interests' => 'Interests',
            'manager' => 'Manager',
            'company' => 'Company',
            'stage' => 'Stage',
            'reg_proj' => 'Reg Proj',
            'specs' => 'Specs',
            'specialization_id' => 'Specialization',
            'password_strength' => 'Password Strength',
            'news_subscription_tophotels' => 'News Subscription Tophotels',
            'news_subscription_turpoisk' => 'News Subscription Turpoisk',
            'news_subscription_rutraveler' => 'News Subscription Rutraveler',
            'news_subscription_travelview' => 'News Subscription Travelview',
            'news_subscription_traveltalk' => 'News Subscription Traveltalk',
            'news_subscription_travelpassport' => 'News Subscription Travelpassport',
            'confirmed' => 'Confirmed',
            'updated' => 'Updated',
            'trash' => 'Trash',
            'hp_id' => 'Hp',
            'hp_updated' => 'Hp Updated',
            'agent_ti_id' => 'Agent Ti',
            'news_subscription_hotelsbroker' => 'News Subscription Hotelsbroker',
            'not_show_age' => 'Not Show Age',
        );
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return User the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    
    public function getUrl(){
        return Yii::app()->createUrl('user/view', array('id' => $this->id)) ;
    }
    
    /**
     * @param $userId
     * @param $size
     * @return string
     */
    public static function getAvatarPath($userId, $size) {
        $tpHost = Yii::app()->travelpassport->serverUrl;
        return "{$tpHost}/avatar/{$size}/{$userId}";
    }
    
    public static function getData($user) {
        return array(
            'id'=>$user->id,
            'name' => $user->name,
            'surname' => $user->surname,
            'nik' => $user->nick,
            'email' => $user->email,
            'url' => $user->getUrl(),
            'ava' => self::getAvatarPath($user->id, User::AVATAR_SIZE_50),
        );
    }
    
   
    
    public function getSendMessageUrl()
    {
        return Yii::app()->createUrl('messageUser/user', array('to' => $this->id)) ;
    }

    /**
     * @return CDbDataReader|mixed|string
     */
    public static function getTotalCount() {
        return self::model()->count("active = 't' AND trash = 'f'");
    }
}

app/controllers/TagController.php
<?php

class TagController extends Controller {
    public function actionIndex() {
        $page = Yii::app()->getRequest()->getParam('page');
        $sort = Yii::app()->getRequest()->getParam('sort');

        $params = array();
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE * $page - Tag::POST_LIMIT_ON_FIRST_LOAD;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Tag::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['tags'] = $this->renderPartial('_tagList', array('dataProvider' => $dataProvider), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('index', array(
            'dataProvider' => $dataProvider,
            'sort' => $sort ? explode('.', $sort) : array('tc', 'desc'),
        ));
    }

    public function actionView($tag) {
        $params = array();
        if (Yii::app()->getRequest()->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
        }

        $dataProvider = Tag::initSearchByTag($tag, $params);
        $postList = $dataProvider->getData();

        $postIds = array();
        foreach ($postList as $post) {
            $postIds[] = $post->id;
        }
        $commentList = Comment::getListByPostIds($postIds, array('tag' => $tag));

        $page = Yii::app()->getRequest()->getParam('page');

        if (Yii::app()->getRequest()->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['items'] = $this->renderPartial('view', array(
                'dataProvider' => $dataProvider,
                'commentList' => $commentList,
                'tag' => $tag,
            ), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('view',array(
            'dataProvider' => $dataProvider,
            'commentList' => $commentList,
            'tag' => $tag,
        ));
    }
} 

app/controllers/UserController.php
<?php

class UserController extends Controller {

    public $layout = 'user';

    /**
     * Моя страница - для авторизированого пользователя
     * @var bool
     */
    public $my = false;

    /**
     *
     * @var User 
     */
    private $_model;

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     * @return User
     */
    public function loadModel($id) {
        $this->_model = User::model()->findByPk($id);
        if ($this->_model === null)
            throw new CHttpException(404, 'Not Found');
        $this->my = $this->_model->id == Yii::app()->user->id;
        return $this->_model;
    }

    public function getModel() {
        if (!$this->_model) {
            $this->loadModel(@$_GET['id']);
        }
        return $this->_model;
    }

    public function actionView($id) {
        $this->loadModel($id);

        $dataProvider = Post::initSearchByUser($id);
        $postList = $dataProvider->getData();

        $postIds = array();
        foreach ($postList as $post) {
            $postIds[] = $post->id;
        }
        $commentList = Comment::getLastByPostId($postIds);
        $likeList = Like::getListByOwnerIds($postIds);

        $this->render('view', array(
            'dataProvider' => $dataProvider,
            'commentList' => $commentList,
            'likeList' => $likeList,
            'userId' => $id,
        ));
    }

    public function actionSubscriptions($id, $t = null) {
        $user = $this->loadModel($id);

        if ($t == 'sub') {
            $data = UserSubscription::getList($id);
        } elseif ($t == 'alloc') {
            $data = AllocationSubscription::getList($id, true);
        } else {
            $data = UserSubscription::getReaders($id);
        }

        $this->render('subscriptions', array(
            'user' => $user,
            'data' => $data,
            'type' => $t,
        ));
    }

    public function actionTag($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $user = User::model()->findByPk($id);

        $page = Yii::app()->getRequest()->getParam('page');
        $sort = Yii::app()->getRequest()->getParam('sort');

        $params['userId'] = $id;
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE * $page - Tag::POST_LIMIT_ON_FIRST_LOAD;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Tag::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['tags'] = $this->renderPartial('_tagList', array('dataProvider' => $dataProvider), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('tag', array(
            'user' => $user,
            'dataProvider' => $dataProvider,
            'sort' => $sort ? explode('.', $sort) : array('tc', 'desc'),
        ));
    }

    public function actionInfo($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $criteria = new CDbCriteria();
        $criteria->with = array(
            'co' => array(
                'select' => 'name',
            ),
            'ct' => array(
                'select' => 'name',
            ),
            'dop' => array(
                'select' => 'facebook, twitter, vkontakte',
            ),
        );
        $user = User::model()->findByPk($id, $criteria);

        $this->render('info', array(
            'user' => $user,
        ));
    }

    public function actionPhoto($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $user = User::model()->findByPk($id);

        $page = Yii::app()->getRequest()->getParam('page');
        $type = Yii::app()->getRequest()->getParam('type', '');

        $params['userId'] = $id;
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Photo::DEFAULT_PHOTO_LIMIT_ON_PAGE;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Photo::DEFAULT_PHOTO_LIMIT_ON_PAGE * $page;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Photo::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['photos'] = $this->renderPartial('_photoList', array('dataProvider' => $dataProvider, 'type' => $type), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }


        $this->render('photo', array(
            'user' => $user,
            'dataProvider' => $dataProvider,
            'type' => $type,
        ));
    }

    public function actionGetData($id) {
        $user = User::model()->findByPk($id);
        if (!$user) {
            throw new CHttpException(404);
        }
        echo json_encode(User::getData($user));
    }

}

app/views/layouts/parts/user/_leftbar_my.php
<?php
//левое меню своё
$user = Yii::app()->controller->model;
/* @var $user User */
?>

<td class="content-td-left">
    <div class="side-menu">
        <div class="side-menu-holder">
            <div class="side-menu-mover">
                <div class="profile profile-info">
                    <table class="profile-tbl">
                        <tr>
                            <td class="profile-td">
                                <a href="<?=$user->getUrl()?>"><img src="<?= User::getAvatarPath(Yii::app()->user->id, User::AVATAR_SIZE_50) ?>" width="60" alt="" /></a>
                            </td>
                            <td class="profile-td">
                                <a class="profile-a" href="#"><?=Yii::t('app','Лента')?></a>
                                <a class="profile-a" href="#"><?=Yii::t('app','Настройки')?></a>
                            </td>
                        </tr>
                    </table>
                </div>
                <div class="leftbar-ttl"><a class="leftbar-ttl-a" href="#"><?=Yii::t('app','Мой профиль')?></a></div>
                <?php $items = array(
                    array(
                        'label' => Yii::t('app','Информация'),
                        'url' => array('user/info', 'id' => $user->id),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-info'),
                    ),
                    array(
                        'label' => Yii::t('app','Лента событий'),
                        'url' => array('user/view', 'id' => $user->id),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-feed leftmenu-li-feed-sel'),
                    ),
                    array(
                        'label' => Yii::t('app','Подписки'),
                        'url' => array('user/subscriptions', 'id' => $user->id),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-guests'),
                    ),
                    array(
                        'label' => Yii::t('app','Актуальные темы'),
                        'url' => array('user/tag', 'id' => $user->id),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-theme'),
                    ),
                    array(
                        'label' => Yii::t('app','Фотографии'),
                        'url' => array('user/photo', 'id' => $user->id),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-pics'),
                    ),
                    array(
                        'label' => Yii::t('app','Оценки сервисов'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-marks'),
                    ),
                    array(
                        'label' => Yii::t('app','Чаты'),
                        'url' => array('messageUser/chats'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-chat'),
                    ),
                    array(
                        'label' => Yii::t('app','Журнал моих действий'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-pen'),
                    ),
                );
                $this->widget('zii.widgets.CMenu', array(
                    'activeCssClass' => 'leftmenu-li-red',
                    'items' => $items,
                    'htmlOptions' => array(
                        'id' => 'left-user-menu',
                        'class' => 'leftbar-ul',
                    ),
                )); ?>
                <?php if (!Yii::app()->user->isGuest): ?>
                    <?php $allocations = AllocationSubscription::getList(Yii::app()->user->id); ?>
                    <?php if ($allocations): ?>
                        <hr class="leftmenu-hr" />
                        <div class="leftbar-ttl"><a class="leftbar-ttl-a" href="#"><?=Yii::t('app','Мои отели')?></a></div>
                        <?php $items = array();
                        foreach ($allocations as $alloc) {
                            $label = $alloc->allocation->name . ' ' . $alloc->allocation->alloccat->name;
                            $label = strlen($label) > 20 ? substr($label, 0, 20) . '...' : $label;
                            $items[] = array(
                                'label' => $label,
                                'url' => array('/allocation/view', 'id' => $alloc->allocation_id),
                                'itemOptions' => array('class' => 'leftmenu-li'),
                                'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-feed leftmenu-li-feed-sel'),
                                'template' => '{menu}<a class="leftmenu-del" href="#"></a>',
                            );
                        }
                        $this->widget('zii.widgets.CMenu', array(
                            'activeCssClass' => 'leftmenu-li-green',
                            'items' => $items,
                            'htmlOptions' => array(
                                'id' => 'left-hotel-menu',
                                'class' => 'leftbar-ul',
                            ),
                        )); ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php $this->widget('UserLanguageMenu'); ?>
                <hr class="leftmenu-hr" />
                <div class="leftbar-ttl"><a class="leftbar-ttl-a" href="#"><?=Yii::t('app','в мире')?></a></div>
                <?php $items = array(
                    array(
                        'label' => Yii::t('app','Найдите отели'),
                        'url' => array('/search/index', 'type' => 'allocation'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-find'),
                    ),
                    array(
                        'label' => Yii::t('app','Лента событий отелей'),
                        'url' => array('/site/index'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-feed leftmenu-li-feed-sel'),
                    ),
                    array(
                        'label' => Yii::t('app','Актуальные темы'),
                        'url' => array('/tag/index'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-theme'),
                    ),
                    array(
                        'label' => Yii::t('app','Новые фотографии'),
                        'url' => array('/photo/index'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-pics'),
                    ),
                    array(
                        'label' => Yii::t('app','Пользователи'),
                        'url' => array('/rating/index'),
                        'itemOptions' => array('class' => 'leftmenu-li'),
                        'linkOptions' => array('class' => 'leftmenu-li-a leftmenu-li-guests'),
                    ),
                );
                $this->widget('zii.widgets.CMenu', array(
                    'activeCssClass' => 'leftmenu-li-red',
                    'items' => $items,
                    'htmlOptions' => array(
                        'id' => 'left-world-menu',
                        'class' => 'leftbar-ul',
                    ),
                )); ?>
                <hr class="leftmenu-hr" />
                <div class="leftbar-ttl"><a class="leftbar-ttl-a" href="#"><?=Yii::t('app','На вашем смартфоне')?></a></div>
                <ul class="leftbar-ul">
                    <li class="leftmenu-li"><a class="leftmenu-li-a leftmenu-li-apple" href="#">AppStore</a></li>
                    <li class="leftmenu-li"><a class="leftmenu-li-a leftmenu-li-andr" href="#">Android Market</a></li>
                </ul>
            </div>
        </div>
    </div>
</td>

app/views/layouts/parts/user/_profile.php
<?php
$this->widget('UserProfile');

app/views/layouts/parts/user/_rightbar_my.php
<td class="content-td-right">
    <div class="rightbar">
        <?php $this->widget('PhotoCloud'); ?>
        <hr size="20" />
        <?php $this->widget('TagCloud'); ?>
        <hr size="20" />
        <?php $this->widget('UserRatingList'); ?>
    </div>
</td>

app/views/layouts/parts/user/_rightbar_other.php
<td class="content-td-right">
    <div class="rightbar">
        <?php $this->widget('PhotoCloud'); ?>
        <hr size="20">
        <?php $this->widget('TagCloud'); ?>
        <hr size="20">
        <a href="#">
            <img src="images/banner.jpg" alt="">
        </a>
    </div>
</td>