app/models/User.php
<?php

/**
 * This is the model class for table "tp.tp_user".
 *
 * The followings are the available columns in table 'tp.tp_user':
 * @property integer $id
 * @property integer $tm_id
 * @property string $nick
 * @property string $email
 * @property string $password
 * @property string $name
 * @property string $surname
 * @property string $patronymic
 * @property string $sex
 * @property integer $city
 * @property integer $country
 * @property string $city_other
 * @property string $date_create
 * @property string $my_updated
 * @property string $avatar_ext
 * @property string $birthday
 * @property string $icq
 * @property string $www
 * @property string $profession
 * @property string $phone
 * @property boolean $active
 * @property boolean $show_email
 * @property boolean $show_icq
 * @property string $description
 * @property string $interests
 * @property boolean $manager
 * @property string $company
 * @property integer $stage
 * @property integer $reg_proj
 * @property string $specs
 * @property integer $specialization_id
 * @property integer $password_strength
 * @property boolean $news_subscription_tophotels
 * @property boolean $news_subscription_turpoisk
 * @property boolean $news_subscription_rutraveler
 * @property boolean $news_subscription_travelview
 * @property boolean $news_subscription_traveltalk
 * @property boolean $news_subscription_travelpassport
 * @property boolean $confirmed
 * @property string $updated
 * @property boolean $trash
 * @property integer $hp_id
 * @property string $hp_updated
 * @property integer $agent_ti_id
 * @property boolean $news_subscription_hotelsbroker
 * @property boolean $not_show_age
 */
class User extends CActiveRecord {
    const AVATAR_SIZE_25 = 25,
        AVATAR_SIZE_50 = 50,
        AVATAR_SIZE_100 = 100,
        AVATAR_SIZE_290 = 290;

    /**
     * @return string the associated database table name
     */
    public function tableName() {
        return 'tp.tp_user';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules() {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('nick, email, password, city, country, date_create, my_updated, updated', 'required'),
            array('tm_id, city, country, stage, reg_proj, specialization_id, password_strength, hp_id, agent_ti_id', 'numerical', 'integerOnly' => true),
            array('nick, email, name, surname, patronymic, city_other, www, interests, company, specs', 'length', 'max' => 255),
            array('password', 'length', 'max' => 32),
            array('avatar_ext', 'length', 'max' => 5),
            array('icq, profession, phone', 'length', 'max' => 100),
            array('sex, birthday, active, show_email, show_icq, description, manager, news_subscription_tophotels, news_subscription_turpoisk, news_subscription_rutraveler, news_subscription_travelview, news_subscription_traveltalk, news_subscription_travelpassport, confirmed, trash, hp_updated, news_subscription_hotelsbroker, not_show_age', 'safe'),
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations() {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'co' => array(self::BELONGS_TO, 'DictCountry', 'country'),
            'ct' => array(self::BELONGS_TO, 'DictCity', 'city'),
            'dop' => array(self::HAS_ONE, 'UserDop', 'id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'tm_id' => 'Tm',
            'nick' => 'Nick',
            'email' => 'Email',
            'password' => 'Password',
            'name' => 'Name',
            'surname' => 'Surname',
            'patronymic' => 'Patronymic',
            'sex' => 'Sex',
            'city' => 'City',
            'country' => 'Country',
            'city_other' => 'City Other',
            'date_create' => 'Date Create',
            'my_updated' => 'My Updated',
            'avatar_ext' => 'Avatar Ext',
            'birthday' => 'Birthday',
            'icq' => 'Icq',
            'www' => 'Www',
            'profession' => 'Profession',
            'phone' => 'Phone',
            'active' => 'Active',
            'show_email' => 'Show Email',
            'show_icq' => 'Show Icq',
            'description' => 'Description',
            'interests' => 'Interests',
            'manager' => 'Manager',
            'company' => 'Company',
            'stage' => 'Stage',
            'reg_proj' => 'Reg Proj',
            'specs' => 'Specs',
            'specialization_id' => 'Specialization',
            'password_strength' => 'Password Strength',
            'news_subscription_tophotels' => 'News Subscription Tophotels',
            'news_subscription_turpoisk' => 'News Subscription Turpoisk',
            'news_subscription_rutraveler' => 'News Subscription Rutraveler',
            'news_subscription_travelview' => 'News Subscription Travelview',
            'news_subscription_traveltalk' => 'News Subscription Traveltalk',
            'news_subscription_travelpassport' => 'News Subscription Travelpassport',
            'confirmed' => 'Confirmed',
            'updated' => 'Updated',
            'trash' => 'Trash',
            'hp_id' => 'Hp',
            'hp_updated' => 'Hp Updated',
            'agent_ti_id' => 'Agent Ti',
            'news_subscription_hotelsbroker' => 'News Subscription Hotelsbroker',
            'not_show_age' => 'Not Show Age',
        );
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return User the static model class
     */
    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
    
    public function getUrl(){
        return Yii::app()->createUrl('user/view', array('id' => $this->id)) ;
    }
    
    /**
     * @param $userId
     * @param $size
     * @return string
     */
    public static function getAvatarPath($userId, $size) {
        $tpHost = Yii::app()->travelpassport->serverUrl;
        return "{$tpHost}/avatar/{$size}/{$userId}";
    }
    
    public static function getData($user) {
        return array(
            'id'=>$user->id,
            'name' => $user->name,
            'surname' => $user->surname,
            'nik' => $user->nick,
            'email' => $user->email,
            'url' => $user->getUrl(),
            'ava' => self::getAvatarPath($user->id, User::AVATAR_SIZE_50),
        );
    }
    
   
    
    public function getSendMessageUrl()
    {
        return Yii::app()->createUrl('messageUser/user', array('to' => $this->id)) ;
    }

    /**
     * @return CDbDataReader|mixed|string
     */
    public static function getTotalCount() {
        return self::model()->count("active = 't' AND trash = 'f'");
    }
}

app/controllers/TagController.php
<?php

class TagController extends Controller {
    public function actionIndex() {
        $page = Yii::app()->getRequest()->getParam('page');
        $sort = Yii::app()->getRequest()->getParam('sort');

        $params = array();
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE * $page - Tag::POST_LIMIT_ON_FIRST_LOAD;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Tag::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['tags'] = $this->renderPartial('_tagList', array('dataProvider' => $dataProvider), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('index', array(
            'dataProvider' => $dataProvider,
            'sort' => $sort ? explode('.', $sort) : array('tc', 'desc'),
        ));
    }

    public function actionView($tag) {
        $params = array();
        if (Yii::app()->getRequest()->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
        }

        $dataProvider = Tag::initSearchByTag($tag, $params);
        $postList = $dataProvider->getData();

        $postIds = array();
        foreach ($postList as $post) {
            $postIds[] = $post->id;
        }
        $commentList = Comment::getListByPostIds($postIds, array('tag' => $tag));

        $page = Yii::app()->getRequest()->getParam('page');

        if (Yii::app()->getRequest()->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['items'] = $this->renderPartial('view', array(
                'dataProvider' => $dataProvider,
                'commentList' => $commentList,
                'tag' => $tag,
            ), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('view',array(
            'dataProvider' => $dataProvider,
            'commentList' => $commentList,
            'tag' => $tag,
        ));
    }
} 

app/controllers/UserController.php
<?php

class UserController extends Controller {

    public $layout = 'user';

    /**
     * Моя страница - для авторизированого пользователя
     * @var bool
     */
    public $my = false;

    /**
     *
     * @var User 
     */
    private $_model;

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     * @return User
     */
    public function loadModel($id) {
        $this->_model = User::model()->findByPk($id);
        if ($this->_model === null)
            throw new CHttpException(404, 'Not Found');
        $this->my = $this->_model->id == Yii::app()->user->id;
        return $this->_model;
    }

    public function getModel() {
        if (!$this->_model) {
            $this->loadModel(@$_GET['id']);
        }
        return $this->_model;
    }

    public function actionView($id) {
        $this->loadModel($id);

        $dataProvider = Post::initSearchByUser($id);
        $postList = $dataProvider->getData();

        $postIds = array();
        foreach ($postList as $post) {
            $postIds[] = $post->id;
        }
        $commentList = Comment::getLastByPostId($postIds);
        $likeList = Like::getListByOwnerIds($postIds);

        $this->render('view', array(
            'dataProvider' => $dataProvider,
            'commentList' => $commentList,
            'likeList' => $likeList,
            'userId' => $id,
        ));
    }

    public function actionSubscriptions($id, $t = null) {
        $user = $this->loadModel($id);

        if ($t == 'sub') {
            $data = UserSubscription::getList($id);
        } elseif ($t == 'alloc') {
            $data = AllocationSubscription::getList($id, true);
        } else {
            $data = UserSubscription::getReaders($id);
        }

        $this->render('subscriptions', array(
            'user' => $user,
            'data' => $data,
            'type' => $t,
        ));
    }

    public function actionTag($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $user = User::model()->findByPk($id);

        $page = Yii::app()->getRequest()->getParam('page');
        $sort = Yii::app()->getRequest()->getParam('sort');

        $params['userId'] = $id;
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE;
            $params['offset'] = Tag::POST_LIMIT_ON_FIRST_LOAD;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Tag::DEFAULT_POST_LIMIT_ON_PAGE * $page - Tag::POST_LIMIT_ON_FIRST_LOAD;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Tag::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['tags'] = $this->renderPartial('_tagList', array('dataProvider' => $dataProvider), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }

        $this->render('tag', array(
            'user' => $user,
            'dataProvider' => $dataProvider,
            'sort' => $sort ? explode('.', $sort) : array('tc', 'desc'),
        ));
    }

    public function actionInfo($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $criteria = new CDbCriteria();
        $criteria->with = array(
            'co' => array(
                'select' => 'name',
            ),
            'ct' => array(
                'select' => 'name',
            ),
            'dop' => array(
                'select' => 'facebook, twitter, vkontakte',
            ),
        );
        $user = User::model()->findByPk($id, $criteria);

        $this->render('info', array(
            'user' => $user,
        ));
    }

    public function actionPhoto($id = null) {
        if (is_null($id)) {
            $id = Yii::app()->user->id;
        }
        $user = User::model()->findByPk($id);

        $page = Yii::app()->getRequest()->getParam('page');
        $type = Yii::app()->getRequest()->getParam('type', '');

        $params['userId'] = $id;
        if (Yii::app()->request->isAjaxRequest) {
            $params['pageSize'] = Photo::DEFAULT_PHOTO_LIMIT_ON_PAGE;
            if (Yii::app()->getRequest()->getParam('all')) {
                $_GET['page'] = 1;
                $params['pageSize'] = Photo::DEFAULT_PHOTO_LIMIT_ON_PAGE * $page;
            }
            if ($tagName = Yii::app()->getRequest()->getParam('tagName')) {
                $params['tagName'] = $tagName;
            }
        }
        $dataProvider = Photo::initSearch($params);

        if (Yii::app()->request->isAjaxRequest) {
            $data['result'] = 'success';
            $data['data']['photos'] = $this->renderPartial('_photoList', array('dataProvider' => $dataProvider, 'type' => $type), true);
            $data['data']['isLastPage'] = $page >= $dataProvider->pagination->pageCount;

            echo CJSON::encode($data);
            Yii::app()->end();
        }


        $this->render('photo', array(
            'user' => $user,
            'dataProvider' => $dataProvider,
            'type' => $type,
        ));
    }

    public function actionGetData($id) {
        $user = User::model()->findByPk($id);
        if (!$user) {
            throw new CHttpException(404);
        }
        echo json_encode(User::getData($user));
    }

}

app/views/user/_photoItem.php
<?php
/* @var $data array */
/* @var $type string */
$src = $data->getFileUrl(Photo::IMAGE_SIZE_129);
if ($type == 'feed') {
    $src = $data->getFileUrl();
}
?>
<li class="userphoto-list-item" id="photo-item-<?= $data->id ?>"<?= $type == 'feed' ? ' style="float: none"' : '' ?>>
    <a href="#" data-img-id="<?= $data->id ?>"><img src="<?= $src ?>" alt="" style="max-width: 525px"></a>
</li>

app/views/user/_photoList.php
<?php
/* @var $this UserController */
/* @var $dataProvider CActiveDataProvider */
/* @var $type string */

$this->widget('zii.widgets.CListView', array(
    'id' => 'photo-list',
    'dataProvider' => $dataProvider,
    'itemView' => '_photoItem',
    'htmlOptions' => array('class' => ''),
    'ajaxUpdate' => false,
    'template' => '{items}',
    'loadingCssClass' => '',
    'itemsTagName' => 'ul',
    'itemsCssClass' => 'userphoto-list items',
    'viewData' => array('type' => $type),
));

app/views/user/_tagItem.php
<?php
/* @var $data array */
?>
<div class="hashtags-table-row">
    <div class="hashtags-table-cell"><a class="hashtags-table-link" href="<?= Yii::app()->createUrl('/tag/view', array('tag' => $data['name'])) ?>"><?= $data['name'] ?></a></div>
    <div class="hashtags-table-cell"><a class="hashtags-table-link" href="#"><?= $data['total_count'] ?></a></div>
    <div class="hashtags-table-cell"><a class="hashtags-table-link" href="#"><?= $data['post_count'] ?></a></div>
    <div class="hashtags-table-cell"><a class="hashtags-table-link" href="#"><?= $data['comment_count'] ?></a></div>
</div>

app/views/user/_tagList.php
<?php
/* @var $this UserController */
/* @var $dataProvider CSqlDataProvider */

$this->widget('zii.widgets.CListView', array(
    'id' => 'tag-list',
    'dataProvider' => $dataProvider,
    'itemView' => '_tagItem',
    'htmlOptions' => array('class' => ''),
    'ajaxUpdate' => false,
    'template' => '{items}',
    'loadingCssClass' => '',
));

app/views/user/info.php
<?php
/* @var $user User */
?>
<div class="userinfo">
    <div class="userinfo-ttl">
        <?=Yii::t('user', 'Личные данные')?> <a href="<?= Yii::app()->createUrl('/user/view', array('id' => $user->id)) ?>"><?= $user->nick ?></a>
    </div>
    <div class="userinfo-section">
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Пол')?></div>
            <div class="userinfo-value"><a href="#">
                <?php if ($user->sex == 'male'): ?>
                     <?=Yii::t('user', 'Мужчина')?>
                <?php elseif ($user->sex == 'female'): ?>
                     <?=Yii::t('user', 'Женщина')?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'День рождения')?></div>
            <div class="userinfo-value">
                <?php if ($user->birthday): ?>
                    <?= Yii::app()->dateFormatter->format("dd MMMM y", $user->birthday) ?> <span class="userinfo-age">— <?= floor((time()-strtotime($user->birthday))/(60*60*24*365.25)) ?> <?=Yii::t('user', 'год')?></span>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Родной город')?></div>
            <div class="userinfo-value">
                <a href="#">
                    <?php if (isset($user->ct->name)): ?>
                        <?= $user->ct->name ?>
                    <?php else: ?>
                        <?=Yii::t('user', 'Не указано')?>
                    <?php endif; ?>
                </a>,
                <a href="#">
                    <?php if (isset($user->co->name)): ?>
                        <?= $user->co->name ?>
                    <?php else: ?>
                        <?=Yii::t('user', 'Не указано')?>
                    <?php endif; ?>
                </a>
            </div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Семейное положение')?></div>
            <div class="userinfo-value"><a href="#"><?=Yii::t('user', 'В активном поиске')?></a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">Языки</div>
            <div class="userinfo-value">
                <a href="#">Русский</a>,
                <a href="#">Английский</a>,
                <a href="#">Французский</a>
            </div>
        </div>
    </div>
    <div class="userinfo-ttl">
        <?=Yii::t('user', 'Контактная информация')?>
    </div>
    <div class="userinfo-section">
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Место жительства')?></div>
            <div class="userinfo-value"><a href="#"><?= $user->co->name ?></a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Телефон')?></div>
            <div class="userinfo-value"><a href="#">
                <?php if ($user->phone): ?>
                    <?= $user->phone ?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">Skype</div>
            <div class="userinfo-value"><a href="#">utafoa</a></div>
        </div>
        <?php if ($user->show_email): ?>
            <div class="userinfo-row">
                <div class="userinfo-label">E-mail</div>
                <div class="userinfo-value"><a href="#">
                        <?php if ($user->email): ?>
                            <?= $user->email ?>
                        <?php else: ?>
                            <?=Yii::t('user', 'Не указано')?>
                        <?php endif; ?>
                    </a></div>
            </div>
        <?php endif; ?>
        <?php if ($user->show_icq): ?>
            <div class="userinfo-row">
                <div class="userinfo-label">ICQ</div>
                <div class="userinfo-value"><a href="#">
                    <?php if ($user->icq): ?>
                        <?= $user->icq ?>
                    <?php else: ?>
                        <?=Yii::t('user', 'Не указано')?>
                    <?php endif; ?>
                </a></div>
            </div>
        <?php endif; ?>
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Веб-сайт')?></div>
            <div class="userinfo-value"><a href="#">
                <?php if ($user->www): ?>
                    <?= $user->www ?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">Facebook</div>
            <div class="userinfo-value"><a href="#">
                <?php if (isset($user->dop->facebook) && $user->dop->facebook): ?>
                    <?= $user->dop->facebook ?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">Вконтакте</div>
            <div class="userinfo-value"><a href="#">
                <?php if (isset($user->dop->vkontakte) && $user->dop->vkontakte): ?>
                    <?= $user->dop->vkontakte ?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">Twitter</div>
            <div class="userinfo-value"><a href="#">
                <?php if (isset($user->dop->twitter) && $user->dop->twitter): ?>
                    <?= $user->dop->twitter ?>
                <?php else: ?>
                    <?=Yii::t('user', 'Не указано')?>
                <?php endif; ?>
            </a></div>
        </div>
        <div class="userinfo-row">
            <div class="userinfo-label">RuTraveller</div>
            <div class="userinfo-value"><a href="#">rutraveller.ru/digitaldog</a></div>
        </div>
    </div>
    <?php if ($user->description): ?>
        <div class="userinfo-ttl">
            <?=Yii::t('user', 'О себе')?>
        </div>
        <div class="userinfo-section">
            <?= $user->description ?>
        </div>
    <?php endif; ?>
    <div class="userinfo-ttl">
        <?=Yii::t('user', 'Подписки и читатели')?>
    </div>
    <div class="userinfo-section subscriptions">
        <div class="userinfo-row">
            <?php $readers = UserSubscription::getReadersCount($user->id); ?>
            <div class="userinfo-label"><?=Yii::t('user', 'Читатели')?></div>
            <div class="userinfo-value"><a href="#"><?=Yii::t('user', '{n} турист|{n} туриста|{n} туристов',$readers)?></a></div>
        </div>
        <div class="userinfo-row">
            <?php $subscriptions = UserSubscription::getSubscriptionsCount($user->id); ?>
            <?php $allocations = AllocationSubscription::getSubscriptionsCount($user->id) ?>
            <div class="userinfo-label"><?=Yii::t('user', 'Читает')?></div>
            <div class="userinfo-value"><a href="#"><?=Yii::t('user', '{n} турист|{n} туриста|{n} туристов',$subscriptions).' '.Yii::t('user', 'и {n} отель|и {n} отеля|и {n} отелей',$allocations)?></a></div>
        </div>
        <?php if (Yii::app()->user->id != $user->id): ?>
            <?php $isSubscribed = UserSubscription::isAlreadySubscribed(Yii::app()->user->id, $user->id); ?>
            <?= CHtml::ajaxLink('<i class="userinfo-feed-icon"></i>' . Yii::t('app', 'Подписаться на ленту'), Yii::app()->createUrl('/subscription/userSubscribe', array('id' => $user->id)), array(
                'dataType' => 'json',
                'context' => 'this',
                'success' => '$.proxy(userSubscribeSuccess, this)',
            ), array('class' => 'userinfo-feed', 'style' => $isSubscribed ? 'display: none' : '')) ?>
            <?= CHtml::ajaxLink('<i class="userinfo-feed-icon"></i>' . Yii::t('app', 'Отписаться'), Yii::app()->createUrl('/subscription/userUnsubscribe', array('id' => $user->id)), array(
                'dataType' => 'json',
                'context' => 'this',
                'success' => '$.proxy(userUnsubscribeSuccess, this)',
            ), array('class' => 'userinfo-feed unsubscribe', 'style' => !$isSubscribed ? 'display: none' : '')) ?>
        <?php endif; ?>
    </div>
    <div class="userinfo-ttl">
         <?=Yii::t('user', 'Активность')?>
    </div>
    <div class="userinfo-section">
        <div class="userinfo-row">
            <div class="userinfo-label"><?=Yii::t('user', 'Онлайн')?></div>
            <div class="userinfo-value"><?=Yii::t('user', 'Был на сайте {date}',array('{date}'=>Yii::app()->getDateFormatter()->format('dd MMM yyyy h:m', time()-3600)))?></div>
        </div>
    </div>
    <div class="userinfo-rss">
      <?=Yii::t('user', 'Перейти к <a href="{url}">ленте событий</a>',array('{url}'=>'/user/'.$user->id))?>   <?= $user->nick ?>
    </div>
</div>
<hr size="20">

app/views/user/photo.php
<?php
/* @var $this UserController */
/* @var $user User */
/* @var $dataProvider CActiveDataProvider */
/* @var $type string */

/* @var EClientScript $clientScript */
$clientScript = Yii::app()->getClientScript();
$baseUrl = Yii::app()->getBaseUrl();
$clientScript->registerScriptFile($baseUrl . '/js/User/photo.js');
$clientScript->registerScriptFile(Yii::app()->getAssetManager()->publish(Yii::getPathOfAlias('application.components.assets.PostList') . '/postList.js'));
?>
<div class="userphoto">
    <div class="userphoto-ttl">
        Фотографии <a href="<?= Yii::app()->createUrl('/user/view', array('id' => $user->id)) ?>"><?= $user->nick ?></a>
        <span class="userphoto-counter">– <?= $dataProvider->totalItemCount ?></span>
    </div>
    <div class="userphoto-search">
        <input class="userphoto-search-input" name="tagName" placeholder="Поиск фотографий по хэштегу" style="width: 365px">
        <?= CHtml::ajaxButton(Yii::t('search', 'Найти фотографии'), Yii::app()->createUrl('/user/photo', array('id' => $user->id)), array(
            'data' => array('page' => 'js:page', 'tagName' => 'js:$(\'input[name="tagName"]\').val()', 'all' => '1'),
            'dataType' => 'json',
            'context' => 'this',
            'success' => '$.proxy(photoSearchSuccess, this)',
        ), array('id' => 'photo-search', 'class' => 'userphoto-search-button', 'style' => 'cursor: pointer')) ?>
    </div>
    <div class="userphoto-layout">
        <?php $this->renderPartial('_photoList', array('dataProvider' => $dataProvider, 'type' => $type)) ?>
    </div>
    <?php if ($dataProvider->totalItemCount > Photo::DEFAULT_PHOTO_LIMIT_ON_PAGE): ?>
        <hr size="20">
        <div class="userphoto-more">
            <img src="/i/comment-bottom-more.png" alt="">
            <?= Yii::t('search', 'Показать') ?> <?= CHtml::ajaxLink(Yii::t('search','следующие 20 фотографий'), Yii::app()->createUrl('/user/photo', array('id' => $user->id)), array(
                'data' => array('page' => 'js:page + 1', 'type' => $type),
                'dataType' => 'json',
                'context' => 'this',
                'success' => '$.proxy(nextPhotoSuccess, this)',
            ), array('id' => 'next-photo')) ?>
        </div>
    <?php endif; ?>
    <hr size="20">
</div>